FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["backend/CodeRunner.Service/CodeRunner.Service.csproj", "backend/CodeRunner.Service/"]
RUN dotnet restore "backend/CodeRunner.Service/CodeRunner.Service.csproj"

COPY . .
RUN dotnet publish "backend/CodeRunner.Service/CodeRunner.Service.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "CodeRunner.Service.dll"]
